services:
  - type: web
    name: bassam-mathematics
    runtime: python
    region: oregon
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
